export const listOfContents = [
  { title: 'Controllers', id: 'controllers' },
  { title: 'Routing', id: 'routing' },
  { title: 'Request object', id: 'request-object' },
  { title: 'Resources', id: 'resources' },
  { title: 'Route-wildcards', id: 'route-wildcards' },
  { title: 'Status code', id: 'status-code' },
  { title: 'ヘッダ', id: 'headers' },
  { title: 'リダイレクト', id: 'redirection' },
  { title: 'パラメータ', id: 'route-parameters' },
  { title: 'サブドメインルーティング', id: 'sub-domain-routing' },
  { title: 'スコープ', id: 'scopes' },
  { title: 'Asynchronicity', id: 'asynchronicity' },
  { title: 'Request payloads', id: 'request-payloads' },
  { title: 'エラー処理', id: 'handling-errors' },
  { title: 'サンプル', id: 'full-resource-sample' },
  { title: 'Getting up and running', id: 'getting-up-and-running' },
  { title: 'Library-specific approach', id: 'library-specific-approach' },
]
