import { TocItem } from '@/types/TocItem'

export default function tocItems(): TocItem[] {
  return [
    {
      section: 'INTRODUCTION',
      sectionUrl: '',
      documents: [],
    },
    {
      section: 'OVERVIEW',
      documents: [
        { title: 'First steps', url: 'first-steps' },
        { title: 'Controllers', url: 'controllers' },
        // { title: 'Providers', url: 'providers' },
        // { title: 'Modules', url: 'modules' },
        // { title: 'Middleware', url: 'middleware' },
        // { title: 'Exception filters', url: 'exception-filters' },
        // { title: 'Pipes', url: 'pipes' },
        // { title: 'Guards', url: 'guards' },
        // { title: 'Interceptors', url: 'interceptors' },
        // { title: 'Custom decorators', url: 'custom-decorators' },
      ],
    },
    // {
    //   section: 'FUNDAMENTALS',
    //   documents: [
    //     { title: 'Custom providers', url: 'fundamentals/custom-providers' },
    //     {
    //       title: 'Asynchronous providers',
    //       url: 'fundamentals/asynchronous-providers',
    //     },
    //     { title: 'Dynamic modules', url: 'fundamentals/dynamic-modules' },
    //     { title: 'Injection scopes', url: 'fundamentals/injection-scopes' },
    //     {
    //       title: 'Circular dependency',
    //       url: 'fundamentals/circular-dependency',
    //     },
    //     { title: 'Module reference', url: 'fundamentals/module-reference' },
    //     {
    //       title: 'Lazy-loading modules',
    //       url: 'fundamentals/lazy-loading-modules',
    //     },
    //     { title: 'Execution context', url: 'fundamentals/execution-context' },
    //     { title: 'Lifecycle events', url: 'fundamentals/lifecycle-event' },
    //     {
    //       title: 'Platform agnosticism',
    //       url: 'fundamentals/platform-agnosticism',
    //     },
    //     { title: 'Testing', url: 'fundamentals/testing' },
    //   ],
    // },
    // {
    //   section: 'TECHNIQUES',
    //   documents: [
    //     { title: 'Configuration', url: 'techniques/configuration' },
    //     { title: 'Database', url: 'techniques/database' },
    //     { title: 'Mongo', url: 'techniques/mongo' },
    //     { title: 'Validation', url: 'techniques/validation' },
    //     { title: 'Caching', url: 'techniques/caching' },
    //     { title: 'Serialization', url: 'techniques/serialization' },
    //     { title: 'Versioning', url: 'techniques/versioning' },
    //     { title: 'Task scheduling', url: 'techniques/task-scheduling' },
    //     { title: 'Queues', url: 'techniques/queues' },
    //     { title: 'Logging', url: 'techniques/logging' },
    //     { title: 'Cookies', url: 'techniques/cookies' },
    //     { title: 'Events', url: 'techniques/events' },
    //     { title: 'Compression', url: 'techniques/compression' },
    //     { title: 'File upload', url: 'techniques/file-upload' },
    //     { title: 'Streaming files', url: 'techniques/streaming-files' },
    //     { title: 'HTTP module', url: 'techniques/http-module' },
    //     { title: 'Session', url: 'techniques/session' },
    //     { title: 'Model-View-Controller', url: 'techniques/mvc' },
    //     { title: 'Performance (Fastify)', url: 'techniques/performance' },
    //     { title: 'Server-Sent Events', url: 'techniques/server-sent-events' },
    //   ],
    // },
    // {
    //   section: 'SECURITY',
    //   documents: [
    //     { title: 'Authentication', url: 'security/authentication' },
    //     { title: 'Authorization', url: 'security/authorization' },
    //     {
    //       title: 'Encryption and Hashing',
    //       url: 'security/encryption-and-hashing',
    //     },
    //     { title: 'Helmet', url: 'security/helmet' },
    //     { title: 'CORS', url: 'security/cors' },
    //     { title: 'CSRF Protection', url: 'security/csrf-protection' },
    //     { title: 'Rate limiting', url: 'security/rate-limiting' },
    //   ],
    // },
    // {
    //   section: 'GRAPHQL',
    //   documents: [
    //     { title: 'Quick start', url: 'graphql/quick-start' },
    //     { title: 'Resolvers', url: 'graphql/resolvers' },
    //     { title: 'Mutations', url: 'graphql/mutations' },
    //     { title: 'Subscriptions', url: 'graphql/subscriptions' },
    //     { title: 'Scalars', url: 'graphql/scalars' },
    //     { title: 'Directives', url: 'graphql/directives' },
    //     { title: 'Interfaces', url: 'graphql/interfaces' },
    //     { title: 'Unions and Enums', url: 'graphql/unions-and-enums' },
    //     { title: 'Field middleware', url: 'graphql/field-middleware' },
    //     { title: 'Mapped types', url: 'graphql/mapped-types' },
    //     { title: 'Plugins', url: 'graphql/plugins' },
    //     { title: 'Complexity', url: 'graphql/complexity' },
    //     { title: 'Extensions', url: 'graphql/extensions' },
    //     { title: 'CLI Plugin', url: 'graphql/cli-plugin' },
    //     { title: 'Generating SDL', url: 'graphql/generating-sdl' },
    //     { title: 'Sharing models', url: 'graphql/sharing-models' },
    //     { title: 'Other features', url: 'graphql/other-features' },
    //     { title: 'Federation', url: 'graphql/federation' },
    //     { title: 'Migration guide', url: 'graphql/migration-guide' },
    //   ],
    // },
    // {
    //   section: 'WEBSOCKETS',
    //   documents: [
    //     { title: 'Gateways', url: 'websockets/gateways' },
    //     { title: 'Exception filters', url: 'websockets/exception-filters' },
    //     { title: 'Pipes', url: 'websockets/pipes' },
    //     { title: 'Guards', url: 'websockets/guards' },
    //     { title: 'Interceptors', url: 'websockets/interceptors' },
    //     { title: 'Adapters', url: 'websockets/adapters' },
    //   ],
    // },
    // {
    //   section: 'MICROSERVICES',
    //   documents: [
    //     { title: 'Overview', url: 'microservices/overview' },
    //     { title: 'Redis', url: 'microservices/redis' },
    //     { title: 'MQTT', url: 'microservices/mqtt' },
    //     { title: 'NATS', url: 'microservices/nats' },
    //     { title: 'RabbitMQ', url: 'microservices/rabbitmq' },
    //     { title: 'Kafka', url: 'microservices/kafka' },
    //     { title: 'gRPC', url: 'microservices/grpc' },
    //     {
    //       title: 'Custom transporters',
    //       url: 'microservices/custom-transporters',
    //     },
    //     { title: 'Exception filters', url: 'microservices/exception-filters' },
    //     { title: 'Pipes', url: 'microservices/pipes' },
    //     { title: 'Guards', url: 'microservices/guards' },
    //     { title: 'Interceptors', url: 'microservices/interceptors' },
    //   ],
    // },
    // {
    //   section: 'STANDALONE APPS',
    //   sectionUrl: 'standalone-applications',
    //   documents: [],
    // },
    // {
    //   section: 'CLI',
    //   documents: [
    //     { title: 'Overview', url: 'cli/overview' },
    //     { title: 'Workspaces', url: 'cli/workspaces' },
    //     { title: 'Libraries', url: 'cli/libraries' },
    //     { title: 'Usage', url: 'cli/usage' },
    //     { title: 'Scripts', url: 'cli/scripts' },
    //   ],
    // },
    // {
    //   section: 'OPENAPI',
    //   documents: [
    //     { title: 'Introduction', url: 'openapi/introduction' },
    //     { title: 'Types and Parameters', url: 'openapi/types-and-parameters' },
    //     { title: 'Operations', url: 'openapi/operations' },
    //     { title: 'Security', url: 'openapi/security' },
    //     { title: 'Mapped Types', url: 'openapi/mapped-types' },
    //     { title: 'Decorators', url: 'openapi/decorators' },
    //     { title: 'CLI Plugin', url: 'openapi/cli-plugin' },
    //     { title: 'Other features', url: 'openapi/other-features' },
    //     { title: 'Migration guide', url: 'openapi/migration-guide' },
    //   ],
    // },
    // {
    //   section: 'RECIPES',
    //   documents: [
    //     { title: 'REPL', url: 'recipes/repl' },
    //     { title: 'CRUD generator', url: 'recipes/crud-generator' },
    //     { title: 'SWC (fast compiler)', url: 'recipes/swc' },
    //     { title: 'Passport (auth)', url: 'recipes/passport' },
    //     { title: 'Hot reload', url: 'recipes/hot-reload' },
    //     { title: 'MikroORM', url: 'recipes/mikroorm' },
    //     { title: 'TypeORM', url: 'recipes/typeorm' },
    //     { title: 'Mongoose', url: 'recipes/mongoose' },
    //     { title: 'Sequelize', url: 'recipes/sequelize' },
    //     { title: 'Router module', url: 'recipes/router-module' },
    //     { title: 'Swagger', url: 'recipes/swagger' },
    //     { title: 'Health checks', url: 'recipes/health-checks' },
    //     { title: 'CQRS', url: 'recipes/cqrs' },
    //     { title: 'Compodoc', url: 'recipes/compodoc' },
    //     { title: 'Prisma', url: 'recipes/prisma' },
    //     { title: 'Serve static', url: 'recipes/serve-static' },
    //     { title: 'Commander', url: 'recipes/commander' },
    //     { title: 'Async local storage', url: 'recipes/async-local-storage' },
    //     { title: 'Automock', url: 'recipes/automock' },
    //   ],
    // },
    // {
    //   section: 'FAQ',
    //   documents: [
    //     { title: 'Serverless', url: 'faq/serverless' },
    //     { title: 'HTTP adapter', url: 'faq/http-adapter' },
    //     { title: 'Keep-Alive connections', url: 'faq/keep-alive-connections' },
    //     { title: 'Global path prefix', url: 'faq/global-path-prefix' },
    //     { title: 'Raw body', url: 'faq/raw-body' },
    //     { title: 'Hybrid application', url: 'faq/hybrid-application' },
    //     { title: 'HTTPS & multiple servers', url: 'faq/multiple-servers' },
    //     { title: 'Request lifecycle', url: 'faq/request-lifecycle' },
    //     { title: 'Common errors', url: 'faq/common-errors' },
    //     { title: 'Examples', url: 'faq/examples' },
    //   ],
    // },
    // {
    //   section: 'DEVTOOLS',
    //   documents: [
    //     { title: 'Overview', url: 'devtools/overview' },
    //     { title: 'CI/CD integration', url: 'devtools/ci-cd-integration' },
    //   ],
    // },
    // {
    //   section: 'MIGRATION GUIDE',
    //   sectionUrl: 'migration-guide',
    //   documents: [],
    // },
    // {
    //   // TODO: 別タブで開くようにすること
    //   section: 'OFFICIAL COURSES',
    //   sectionUrl: 'https://courses.nestjs.com/',
    //   documents: [],
    // },
    // {
    //   section: 'DISCOVER',
    //   documents: [{ title: 'Who is using Nest?', url: 'discover/companies' }],
    // },
    // {
    //   section: 'SUPPORT US',
    //   sectionUrl: 'support',
    //   documents: [],
    // },
  ]
}
